baseURL: 'https://xorkevin.com/'
languageCode: 'en-us'
title: 'xorkevin'
theme: 'core'
summaryLength: 8
pluralizelisttitles: 'false'
pygmentsCodeFences: true
blackfriday:
  fractions: false
  hrefTargetBlank: true
  nofollowLinks: true
  noreferrerLinks: true
footnoteReturnLinkContents: '&larrhk;'
copyright: 2018
permalinks:
  blog: '/:section/:year/:month/:title'
params:
  author: 'xorkevin'
