baseURL: 'https://xorkevin.com/'
languageCode: 'en-us'
title: 'xorkevin'
theme: 'core'
summaryLength: 8
pluralizelisttitles: 'false'
pygmentsCodeFences: true

permalinks:
  blog: '/:section/:year/:month/:title'
