baseURL: 'https://xorkevin.com/'
languageCode: 'en-us'
title: 'xorkevin'
theme: 'core'
pluralizelisttitles: 'false'
footnoteReturnLinkContents: '&larrhk;'
copyright: 2018
permalinks:
  blog: '/:section/:year/:month/:title'
params:
  author: 'xorkevin'
  headerbackground: '/img/home/background.jpg'
