name = "core"
license = "MPL-2.0"
licenselink = "https://github.com/xorkevin/core/blob/master/LICENSE"
description = "a simple blog theme for hugo"
homepage = "http://github.com/xorkevin/core"
tags = []
features = []
min_version = "0.55"

[author]
  name = "Kevin Wang"
  homepage = "xorkevin.com"
